---
title: Fab13 Fabricating Society
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: fab13@fablabsantiago.org
description: Fab 13 is the 13th international Fab Lab Conference in Santiago de Chile,
  jul 31 - aug 6 2017
color:
  blacks: 141414
  whites: f9f9f9
  andeanwhite: dce6da
  andeanceleste: a8dadc
  andeanblue: 457b9d
  andeannavy: 1d3557
  andeanpink: eb5f69
  andeanred: e63946
  andeansand: FAFBF9
fonts:
  primary: Tstarr
  secondary: Nunito
  texts: Nunito
social:
- title: twitter
  url: https://twitter.com/fab13santiago
- title: facebook
  url: https://www.facebook.com/fab13santiago
- title: instagram
  url: https://www.instagram.com/fab13santiago/
- title: envelope
  url: mailto:fab13@fablabsantiago.org
address:
- line: The Fab Foundation
- line: 50 Milk St. 16th Floor
- line: Boston MA 02109
- line: Tel +1 857 333 7777
markdown: kramdown
permalink: pretty
gems:
- kramdown
urlimg: "/img/"
