- name: Aplica para ser voluntario
  short: "Apply to volunteer at the biggest Digital Fabrication event in the world!"
  url: "https://docs.google.com/a/fab.city/forms/d/e/1FAIpQLSeKWl31p9fOxAetyjoDfe1p7Aejb3E_hTNgj3GYaiDz7AsMzQ/viewform"
  placement: right

- name: Resultado de la selección de workshops
  short: Revisa si tu workshop fue elegido para llevarse a cabo en Fab13!
  url: /selected_workshops.pdf
  placement: right

