- name: 'Soon we will publish the selected volunteer!'
  short:
  url:
  placement: right
- name: Workshop selection results
  short: 'Check out if your workshop was selected to be held at Fab13!'
  url: /selected_workshops.pdf
  placement: right