- name: 'How to participate'
  short: Fab Events (FAB13) are a way to integrate all the knowledge acquired during the year of over more than 1.100 Fab Labs in the world. The participation for content is based on the active participation of those members or others, that see this space as a showroom for their projects, workshops, labs, and acknowledge that all the work will be seen and appreciated by all the people in the network. The key is basically the networking tutors and volunteers can make in this new world of digital fabrication.
  url:
  placement: right
- name: Workshop selection
  short: 'Check out if your workshop was selected to be held at Fab13!'
  url: 
  placement: right
- name: Working Group Selection
  short: 'Check out if your workshop was selected to be held at Fab13!'
  url: 
  placement: right